### ISSUE TITLE
AddressSanitizer: memcpy-param-overlap:  in salt-channel-c/src/salt.c:484

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/salt-channel-c#17]
When build with AddressSanitizer (GCC 4.9.4)
tests/salt_write fails in test salt_write_message_buff_size()
with error 
==8354==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges

To reproduce pls use branch "ppmag-review",  run ./debug-san.sh

**Comment by sijohans** [comment]
Fixed. it was the test case itself who was written so that this happend. Will merge in your adress sanitizer stuff also. I also found a "FindSodium.cmake" script to make build with libsodium easier.
