### ISSUE TITLE
CMocka is not found on Fedora

### ISSUE THREAD

**Issue by bundgaard** [assaabloy-ppi/salt-channel-c#37]
Hello,

I recently found out that the cmocka shared object is not in build/external/cmocka/lib on fedora systems, but build/external/cmocka/lib64/

Would be nice if that would be added to the cmake to be found automatically.

Thanks

**Comment by sijohans** [comment]
Hello, I'll take a look into this.

**Comment by sijohans** [comment]
Do you have any suggestions one this one?

**Comment by sijohans** [comment]
I've changed the build system to not install cmocka for you. Instead you have to install it to your system (in order to test). Please try that and confirm if it works.
