### ISSUE TITLE
Support for blocksizes larger than 65kbyte

### ISSUE THREAD

**Issue by AndreasHansson73** [assaabloy-ppi/salt-channel-c#40]
The call to salt_write_next takes a size parameter that is uint16_t. This limits the size of the blocks to write to 65kbyte. It would be nice to be able to read and write larger blocks.

**Comment by sijohans** [comment]
I've been working on this a little bit, please see branch https://github.com/assaabloy-ppi/salt-channel-c/tree/fix-size-truncation
