### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by jv813yh** [assaabloy-ppi/salt-channel-c#49]
Is there also an implementation for windows?

**Comment by franslundberg** [comment]
I suppose the C-code could run on Windows as well. Please, explain a bit more. Do you require the code to compile on another compiler? For a specific Windows API?

**Comment by jv813yh** [comment]
My intention is to test the Salt-channel-c communication protocol between two different operating systems, such as Linux (Ubuntu) and Windows 10. So I'm thinking about how to compile and link your Salt-channel-c project to Windows. Do you have any ideas? Can you help me ? Please.

**Comment by jakkli** [comment]
I am not sure if that is a feasible solution for you, but it is possible to compile and run Salt Channel on Windows using Cygwin environment.

**Comment by sijohans** [comment]
The C code is generic and should run on windows. The development environment and example is for posix based systems. You also need to compile the crypto library, i recommend libsodium, see: https://libsodium.gitbook.io/doc/installation

The examples client and server echo are coded for posix systems. I have never done this in windows but i guess there are a lot of examples out there.

Another approach for you would be to use the Java version of salt-channel: https://github.com/assaabloy-ppi/salt-channel
Easier to use

**Comment by jv813yh** [comment]
I'd rather work with C. I want to ask if I can use the TweetNaCl library instead of Libsodium?

**Comment by sijohans** [comment]
Yes, it is much slower however. You can use https://github.com/assaabloy-ppi/salt-channel-c/tree/master/src/external/tweetnacl_modified

**Comment by jv813yh** [comment]
I want to use client / server communication, use the tcp protocol and salt-channel protocol to secure communication on the windows operating system and use the tweetnacl library. Do you think that's real?

**Comment by jv813yh** [comment]
Any good source where I explain the creation of a tcp / ip connection in C language in the Windows operating system, where I could then use the protocol salt-channel to secure the channel?

**Comment by jv813yh** [comment]
Hello,
You have not added a chunking format in the salt channel over TCP section .

**Comment by jv813yh** [comment]
I created a TCP connection on Windows 10 using Winsock, Winsock by default automatically without the user's knowledge forged a handshake between the communicating parties. I want to ask, do I need to access the raw drawers if I want to work with the salt-channel protocol, or does the handshake perform the salt channel change automatically?

**Comment by jv813yh** [comment]
I would like to ask you why the book Libsodium is used. TweetNacl library does not provide sufficient cryptographic algorithms?

**Comment by sijohans** [comment]
As mentioned above, tweetnacl works well but is very slow. You can use this: https://github.com/assaabloy-ppi/salt-channel-c/tree/master/src/external/tweetnacl_modified

This library is hard coded to add the four size bytes as defined in salt-channel over TCP here: https://github.com/assaabloy-ppi/salt-channel/blob/master/files/spec/salt-channel-v2-final2.md#salt-channel-over-tcp

Are you referring to the TCP handshake?

The handshake function will automatically do the handshake given that you have provided functions for I/O (in yours case that works with the Winsock library). I have never worked with sockets on windows (and i don't have a windows computer to test is), but i think the posix example could help you a lot:
https://github.com/assaabloy-ppi/salt-channel-c/tree/master/examples

Would have been nice with windows examples also, and a CMake file that works for both.

**Comment by jv813yh** [comment]
> As mentioned above, tweetnacl works well but is very slow. You can use this: https://github.com/assaabloy-ppi/salt-channel-c/tree/master/src/external/tweetnacl_modified
> 
> This library is hard coded to add the four size bytes as defined in salt-channel over TCP here: https://github.com/assaabloy-ppi/salt-channel/blob/master/files/spec/salt-channel-v2-final2.md#salt-channel-over-tcp
> 
> Are you referring to the TCP handshake?
> 
> The handshake function will automatically do the handshake given that you have provided functions for I/O (in yours case that works with the Winsock library). I have never worked with sockets on windows (and i don't have a windows computer to test is), but i think the posix example could help you a lot:
> https://github.com/assaabloy-ppi/salt-channel-c/tree/master/examples
> 
> Would have been nice with windows examples also, and a CMake file that works for both.

When the client calls the salti_create_m1 () function, the hndsk_buffer stores the hash of the M1 message and where is the M1 message structure stored, which will be sent through the channel for the server?

**Comment by sijohans** [comment]
In the readme file there is host and client handshake procedure:
https://github.com/assaabloy-ppi/salt-channel-c#host-handshake-procedure and https://github.com/assaabloy-ppi/salt-channel-c#client-handshake-procedure

There you can see how the handshake buffer look like during the different steps.

**Comment by jv813yh** [comment]
I try to create a handshake myself from the functions needed to create, but if I call the salti_create_m1 () or salti_create_m2 () functions, then the functions from salti_handle_m2 () and salti_handle_m1 () print out errors. For example, on the client side, I did this by calling the salt_create (), salt_create_signature (), salt_init_session () functions, and then calling the salti_create_m1 (& channel, & hndsk_buffer [SALT_SIG_PREFIX_OFFSET], & size, &hndsk_buffer[SALT_M2_SIZE_OFFSET];
Hndsk_buffer is an auxiliary buffer where I want to store data and hashes and similar necessary things. According to the documentation, the data created for M1 management should be in the hndsk_buffer [] field from the SALT_SIG_PREFIX_OFFSET element, and the hash should be stored from the beginning in hndsk_buffer. Everything runs out it looks nice to the naked eye, but if I go to check it with the contents of the salti_handle_m1 () function, it gives me errors. Don't know why? Did I misunderstand the functions of salti_create_m1 () and m2_ ()?

**Comment by sijohans** [comment]
It was quite some time since i wrote this, i don't remember all the details (would probably design some things different today). Is there a particular reason for you to implement this on your own instead of using the provided functions?

To verify correct created M1 etc, you can use specific key pairs for signature and ephemeral, look here: https://github.com/assaabloy-ppi/salt-channel-c/blob/master/tests/test_data.c

I Will look into this a little bit to see if i can help you. You could just do some naive approach to start with and do a lot of dumping of the handshake buffer to see what is happenings with that one to get a better understanding. There might be some typeos in the handshake procedure description.

**Comment by sijohans** [comment]
Something like this you should be able to do and  then modify as you with:
```c
#include <stdio.h>
#include <assert.h>
#include <string.h>

#include "salt.h"
#include "salti_util.h"
#include "salti_handshake.h"
#include "test_data.h"

#define SALT_M1_HASH_OFFSET                     (72U)
#define SALT_M2_HASH_OFFSET                     (136U)
#define SALT_M2_HOST_OFFSET                     (200U)

#define HEXDUMP(data, size) hexdump(#data, data, size)
void hexdump(const char *str, const uint8_t *data, uint32_t size)
{
    printf("%s: ", str);
    for (uint32_t i = 0; i < size; i++) {
        printf("%02x", data[i]);
    } printf("\r\n");
}

int main(void)
{

    uint8_t client_buffer[SALT_HNDSHK_BUFFER_SIZE];
    uint8_t server_buffer[SALT_HNDSHK_BUFFER_SIZE];

    salt_example_session_1_t *test_data = &salt_example_session_1_data;
    uint8_t dummy;

    salt_channel_t client_channel;
    salt_create(&client_channel, SALT_CLIENT, (salt_io_impl) &dummy, (salt_io_impl) &dummy, NULL);
    salt_set_signature(&client_channel, test_data->client_sk_sec);

    salt_channel_t server_channel;
    salt_create(&server_channel, SALT_SERVER, (salt_io_impl) &dummy, (salt_io_impl) &dummy, NULL);
    salt_set_signature(&server_channel, test_data->host_sk_sec);

    salt_init_session_using_key(&client_channel, client_buffer, sizeof(client_buffer),
                                test_data->client_ek_pub, test_data->client_ek_sec);

    salt_init_session_using_key(&server_channel, server_buffer, sizeof(server_buffer),
                                test_data->host_ek_pub, test_data->host_ek_sec);

    uint32_t size = 0;
    salti_create_m1(&client_channel,
                    &client_channel.hdshk_buffer[SALT_M2_HASH_OFFSET],
                    &size,
                    &client_channel.hdshk_buffer[SALT_M1_HASH_OFFSET],
                    NULL);

    assert(memcmp(&client_channel.hdshk_buffer[SALT_M2_HASH_OFFSET], test_data->m1, size) == 0);
    HEXDUMP(&client_channel.hdshk_buffer[SALT_M2_HASH_OFFSET], size);

    salti_handle_m2(&server_channel,
                    &server_channel.hdshk_buffer[SALT_M2_HASH_OFFSET],
                    size, &server_channel.hdshk_buffer[SALT_M2_HASH_OFFSET]);


    salti_create_m2(&server_channel,
                    &server_channel.hdshk_buffer[SALT_M2_HOST_OFFSET],
                    &size,
                    &server_channel.hdshk_buffer[SALT_M2_HASH_OFFSET]);

    assert(memcmp(&server_channel.hdshk_buffer[SALT_M2_HOST_OFFSET], test_data->m2, size) == 0);
    HEXDUMP(&server_channel.hdshk_buffer[SALT_M2_HOST_OFFSET], size);

    salti_handle_m2(&client_channel,
                    &client_channel.hdshk_buffer[SALT_M2_HASH_OFFSET],
                    size, &client_channel.hdshk_buffer[SALT_M2_HASH_OFFSET]);

    assert(memcmp(server_channel.ek_common, client_channel.ek_common, 32) == 0);

    return 0;
}
```

**Comment by jv813yh** [comment]
I did it similarly to the example you gave, but when you notice that the salti_handle_m1 () function does not perform the necessary operations such as creating an M1 hash message for later authentication, also copying the clients public ephemeral encryption key to p_channel_hdsk_buffer and so on. Also, the salti_handle_m2 () function does not create an M2 message hash or ek_common, and so on. You can see that you are calling the salt_handle_m2 () function, and when you list client_channel.ek_common, which should already contain a symmetrically shared key, it is empty. I ran into these problems because I don't understand where the problem is, and I turned to you if you couldn't help me. So far I solve this so that these functions handle_m1 and handle_m2 (), where the required cryptographic operations are performed, I implemented in my own functions, which look like they work (I still don't know because I'm currently trying to encrypt the M3 message) And to your question why it's so complicated I do, I would like to implement the Salt protocol on Windows OS on the TCP layer, but in the example that is given, you use socket programming using pthreads, but on Windows I have worked with socket programming using the select () function, which is offered by the winsock library .h, and there are some issues that do not occur when working with pthreads on Unix systems. So I wanted to go into the Salt protocol in detail so that I could solve these problems properly. You may be wondering why I don't want to work with pthreads on Windows, but I think I'll be right when I say that working with pthreads on Windows is completely different from Unix systems and much more complicated.

**Comment by jv813yh** [comment]
To help you understand me correctly, the problem is that the conditions in the functions salt_handle_m1 () and handle_m2 () evaluate that the message does not contain the expected constants and so on the correct positions, but when I create the individual messages, I create them exactly as it's in the source code, so just like you showed in this example. And when I look at these individual reports in detail, they fill up nicely according to the procedures given in the source codes or documentation.

**Comment by sijohans** [comment]
Any progress on this?
Using the included handshake function should not be any problem in windows. You just need to do the listen,accept, read and write implementations.

**Comment by jv813yh** [comment]
Yes, I have already found out where I made mistakes and successfully created a SALT handshake between the client and the server without the TCP sublayer and I have already deployed the SALT protocol on the TCP layer but I am considering how to write write_impl and read_impl implementations to use multiplex sockets on Windows using winsock API. I'm thinking of including the select () function in the code.

**Comment by jv813yh** [comment]
I want to ask, I also have a problem. I deployed the application protocol salt channelv2 on the TCP communication channel, I use the select method for multiple processing of clients by the server. However, I also have a problem that it still only serves me the last connected client. Have you encountered this problem?

Application link:
https://github.com/jv813yh/tcp_salt

**Comment by sijohans** [comment]
I have never used this in windows and i don't have much knowledge about socket programming there. I guess the select method is similar to how it is used in posix based systems. You need to figure out what you want your application to do and then learn how to get this behaviour with select. I would start by just learning how to use select. How can you use it to allow for multiple connections and sending receiving any data between server and client? What context do you need to store for each client?

Further, what is a client/server session in your case. A handshake and one message? Multiple messages? What states do you have between each client and the server? E.g., with select you can know this:

- Someone connected, you can now accept that to get a new socket to be used to send/receive data on the TCP layer.
- Data is available to read from one of the connected clients
- Some client disconnected

Each client connected is associated with a salt channel state. I.e.,
- A client connects, you can now send and receive data
- You now need to do a handshake with that client
- When the handshake is done, you can send and read application data

Typical states for a connected client could be e.g.: HANDSHAKING, HANDSHAKE_DONE, ERROR/DISCONNECTED. Depending on the event from select and the state of the client, you should either continue handshaking or read/write application messages.

I would start by just learning how to use select to accept multiple connections, maintaining that and just learning how to do read/write operations (on the socket layer) with each client.

**Comment by jv813yh** [comment]
I have already managed to study the select () function and the service of several clients at once. I deployed a salt protocol on the TCP channel in Windows, where the server provides a chat room for connected clients. After a successful Salt handshake, the server can serve several clients at the same time. I am still fine-tuning the program details.
